# Generated by Django 2.2.12 on 2022-05-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='pthoto_main',
            new_name='photo_main',
        ),
    ]
